package Applications;

import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

public final class IndexFrame extends javax.swing.JFrame {

    /* Creates new form IndexPage */
    public IndexFrame() {
        // This method is called from within the constructor
        // to initialize the form.
        initComponents();

        //Sets whether this frame is resizable by the user.
        this.setResizable(false);

        permSetting();  //Call "permissionSetting()" Method
    }

    public void permSetting() {
        if ("Employee".equals(LogIns.userType)) {
            jMenuItemTeacherDetails.setEnabled(false);
            jMenuItemLibrary.setEnabled(false);
            jMenuItemUserSettings.setEnabled(false);
            jLabelUsrType.setText("Employee");
        } else if ("Librarian".equals(LogIns.userType)) {
            jMenuItemTeacherDetails.setEnabled(false);
            jMenuItemUserSettings.setEnabled(false);
            jLabelUsrType.setText("Librarian");
        } else {
            jLabelUsrType.setText("Admin");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelSchoolName = new javax.swing.JLabel();
        jLabelAppName = new javax.swing.JLabel();
        jLabelSchoolType = new javax.swing.JLabel();
        jLabelfor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneINFO = new javax.swing.JEditorPane();
        jButtonAboutThisSys = new javax.swing.JButton();
        jButtonAboutUs = new javax.swing.JButton();
        jLabelUsrType = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemStuInfo = new javax.swing.JMenuItem();
        jMenuItemTeacherDetails = new javax.swing.JMenuItem();
        jMenuItemLibrary = new javax.swing.JMenuItem();
        jMenuItemUserSettings = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuInfoChart = new javax.swing.JMenu();
        jMenuItemView = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemWindows = new javax.swing.JMenuItem();
        jMenuItemClassic = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMotif = new javax.swing.JMenuItem();
        jMenuItemNimbus = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabelSchoolName.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabelSchoolName.setForeground(new java.awt.Color(192, 0, 0));
        jLabelSchoolName.setText("Adik Shadik");

        jLabelAppName.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabelAppName.setForeground(new java.awt.Color(200, 0, 0));
        jLabelAppName.setText("School Management System");

        jLabelSchoolType.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabelSchoolType.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSchoolType.setText("Primary and High School");

        jLabelfor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabelfor.setForeground(new java.awt.Color(200, 0, 0));
        jLabelfor.setText("for");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelSchoolName)
                    .addComponent(jLabelAppName)
                    .addComponent(jLabelfor)
                    .addComponent(jLabelSchoolType))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSchoolName)
                .addGap(4, 4, 4)
                .addComponent(jLabelAppName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelfor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSchoolType)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jEditorPaneINFO);

        jButtonAboutThisSys.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAboutThisSys.setText("About This System");
        jButtonAboutThisSys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutThisSysActionPerformed(evt);
            }
        });

        jButtonAboutUs.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButtonAboutUs.setText("About Us");
        jButtonAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutUsActionPerformed(evt);
            }
        });

        jLabelUsrType.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabelUsrType.setForeground(new java.awt.Color(255, 0, 0));

        jMenuFile.setText("File");

        jMenuItemStuInfo.setText("Student Information");
        jMenuItemStuInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemStuInfoActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemStuInfo);

        jMenuItemTeacherDetails.setText("Teacher Details");
        jMenuItemTeacherDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTeacherDetailsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemTeacherDetails);

        jMenuItemLibrary.setText("Library Information");
        jMenuItemLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLibraryActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLibrary);

        jMenuItemUserSettings.setText("User Settings");
        jMenuItemUserSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUserSettingsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemUserSettings);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenu1.setText("View");

        jMenuInfoChart.setText("Information Chart");

        jMenuItemView.setText("VIEW");
        jMenuItemView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewActionPerformed(evt);
            }
        });
        jMenuInfoChart.add(jMenuItemView);

        jMenu1.add(jMenuInfoChart);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Themes");

        jMenuItemWindows.setText("Windows");
        jMenuItemWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemWindowsActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemWindows);

        jMenuItemClassic.setText("Classic");
        jMenuItemClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClassicActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemClassic);
        jMenu2.add(jSeparator1);

        jMenuItemMotif.setText("Motif");
        jMenuItemMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMotifActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMotif);

        jMenuItemNimbus.setText("Nimbus");
        jMenuItemNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNimbusActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemNimbus);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAboutThisSys)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAboutUs)))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelUsrType, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUsrType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAboutThisSys)
                    .addComponent(jButtonAboutUs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Open this form in Center
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItemTeacherDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTeacherDetailsActionPerformed
        try {
            // Call "Teacher Details" Form By Its Own Object
            TeacherDetails TeaDetail = new TeacherDetails();
            TeaDetail.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemTeacherDetailsActionPerformed

    private void jMenuItemLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLibraryActionPerformed
        try {
            // Call "LibraryBookInfo" Form By Its Own Object
            LibraryBookInfo lib = new LibraryBookInfo();
            lib.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemLibraryActionPerformed

    private void jMenuItemStuInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemStuInfoActionPerformed
        try {
            // Call "Student Information" Form By Its Own Object
            StudentInformation StuInfo = new StudentInformation();
            StuInfo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemStuInfoActionPerformed

    private void jMenuItemUserSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUserSettingsActionPerformed
        try {
            // Call "User Settings" Form By Its Own Object
            UserSettings UsrSetting = new UserSettings();
            UsrSetting.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemUserSettingsActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // "Exit" Menu Item
        System.exit(0);  //Terminates the currently running Java Virtual Machine.
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewActionPerformed
        try {
            InfoChart crtInfo = new InfoChart();
            crtInfo.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemViewActionPerformed

    private void jMenuItemWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemWindowsActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemWindowsActionPerformed

    private void jMenuItemClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClassicActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemClassicActionPerformed

    private void jMenuItemMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMotifActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemMotifActionPerformed

    private void jMenuItemNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNimbusActionPerformed
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
            SwingUtilities.updateComponentTreeUI(this);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemNimbusActionPerformed

    private void jButtonAboutThisSysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutThisSysActionPerformed
        try {
            jEditorPaneINFO.setPage(getClass().getResource("/WebPages/AboutThisSys.html"));
        } catch (IOException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
            jEditorPaneINFO.setText("Invalid URL ...");
        }
    }//GEN-LAST:event_jButtonAboutThisSysActionPerformed

    private void jButtonAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutUsActionPerformed
        try {
            jEditorPaneINFO.setPage("http://localhost");
        } catch (IOException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
            jEditorPaneINFO.setText("Check your internet connection ...");
        }
    }//GEN-LAST:event_jButtonAboutUsActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndexFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndexFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAboutThisSys;
    private javax.swing.JButton jButtonAboutUs;
    private javax.swing.JEditorPane jEditorPaneINFO;
    private javax.swing.JLabel jLabelAppName;
    private javax.swing.JLabel jLabelSchoolName;
    private javax.swing.JLabel jLabelSchoolType;
    private javax.swing.JLabel jLabelUsrType;
    private javax.swing.JLabel jLabelfor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuInfoChart;
    private javax.swing.JMenuItem jMenuItemClassic;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLibrary;
    private javax.swing.JMenuItem jMenuItemMotif;
    private javax.swing.JMenuItem jMenuItemNimbus;
    private javax.swing.JMenuItem jMenuItemStuInfo;
    private javax.swing.JMenuItem jMenuItemTeacherDetails;
    private javax.swing.JMenuItem jMenuItemUserSettings;
    private javax.swing.JMenuItem jMenuItemView;
    private javax.swing.JMenuItem jMenuItemWindows;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
