package Applications;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class InfoChart extends javax.swing.JFrame {

    Connection DBCon;

    /* Creates new form InfoChart */
    public InfoChart() throws SQLException {
        // This method is called from within the constructor
        // to initialize the form.
        initComponents();

        //Sets whether this frame is resizable by the user.
        this.setResizable(false);

        //Call Database Connection Driver
        DBCon = DatabaseConnection.ClsDatabaseConnection.methodDatabaseConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTitle = new javax.swing.JPanel();
        jLabelTitleName = new javax.swing.JLabel();
        jTabbedPaneIndexInfo = new javax.swing.JTabbedPane();
        jPanelStuInfo = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStuInfo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButtonStuClear = new javax.swing.JButton();
        jButtonStuADD = new javax.swing.JButton();
        jButtonStuView = new javax.swing.JButton();
        jPanelBookInfo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBookInfo = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButtonBookClear = new javax.swing.JButton();
        jButtonBookADD = new javax.swing.JButton();
        jButtonBookView = new javax.swing.JButton();
        jPanelTecInfo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableStuInfo1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jButtonTecClear = new javax.swing.JButton();
        jButtonTecADD = new javax.swing.JButton();
        jButtonTecView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanelTitle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jLabelTitleName.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabelTitleName.setForeground(new java.awt.Color(192, 0, 0));
        jLabelTitleName.setText("Information Chart");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitleName)
                .addContainerGap())
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitleName)
                .addContainerGap())
        );

        jTabbedPaneIndexInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jPanelStuInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jTableStuInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jTableStuInfo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableStuInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "Student Name", "Class", "Section", "Major"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableStuInfo);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jButtonStuClear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonStuClear.setText("Clear");
        jButtonStuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuClearActionPerformed(evt);
            }
        });

        jButtonStuADD.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonStuADD.setText("ADD");
        jButtonStuADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuADDActionPerformed(evt);
            }
        });

        jButtonStuView.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonStuView.setText("View");
        jButtonStuView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStuViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonStuView, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonStuClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonStuADD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonStuView)
                    .addComponent(jButtonStuClear)
                    .addComponent(jButtonStuADD))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelStuInfoLayout = new javax.swing.GroupLayout(jPanelStuInfo);
        jPanelStuInfo.setLayout(jPanelStuInfoLayout);
        jPanelStuInfoLayout.setHorizontalGroup(
            jPanelStuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanelStuInfoLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(194, Short.MAX_VALUE))
        );
        jPanelStuInfoLayout.setVerticalGroup(
            jPanelStuInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStuInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneIndexInfo.addTab("Student Information", jPanelStuInfo);

        jPanelBookInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jTableBookInfo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableBookInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Title", "Student ID", "Borrow Date", "Return Date"
            }
        ));
        jScrollPane2.setViewportView(jTableBookInfo);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jButtonBookClear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonBookClear.setText("Clear");
        jButtonBookClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookClearActionPerformed(evt);
            }
        });

        jButtonBookADD.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonBookADD.setText("ADD");
        jButtonBookADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookADDActionPerformed(evt);
            }
        });

        jButtonBookView.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonBookView.setText("View");
        jButtonBookView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBookView, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonBookClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonBookADD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBookView)
                    .addComponent(jButtonBookClear)
                    .addComponent(jButtonBookADD))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBookInfoLayout = new javax.swing.GroupLayout(jPanelBookInfo);
        jPanelBookInfo.setLayout(jPanelBookInfoLayout);
        jPanelBookInfoLayout.setHorizontalGroup(
            jPanelBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelBookInfoLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBookInfoLayout.setVerticalGroup(
            jPanelBookInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneIndexInfo.addTab("Book Information", jPanelBookInfo);

        jPanelTecInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));

        jTableStuInfo1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        jTableStuInfo1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTableStuInfo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Teacher Name", "Member", "Department"
            }
        ));
        jScrollPane3.setViewportView(jTableStuInfo1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        jButtonTecClear.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonTecClear.setText("Clear");
        jButtonTecClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTecClearActionPerformed(evt);
            }
        });

        jButtonTecADD.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonTecADD.setText("ADD");
        jButtonTecADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTecADDActionPerformed(evt);
            }
        });

        jButtonTecView.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButtonTecView.setText("View");
        jButtonTecView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTecViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonTecView, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonTecClear, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButtonTecADD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTecView)
                    .addComponent(jButtonTecClear)
                    .addComponent(jButtonTecADD))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelTecInfoLayout = new javax.swing.GroupLayout(jPanelTecInfo);
        jPanelTecInfo.setLayout(jPanelTecInfoLayout);
        jPanelTecInfoLayout.setHorizontalGroup(
            jPanelTecInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTecInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelTecInfoLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTecInfoLayout.setVerticalGroup(
            jPanelTecInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTecInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneIndexInfo.addTab("Teacher Information", jPanelTecInfo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPaneIndexInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPaneIndexInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonStuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuClearActionPerformed
        // "Clear" Button (Student Information)
        DefaultTableModel modelStudent = (DefaultTableModel) jTableStuInfo.getModel();
        modelStudent.setRowCount(0);
    }//GEN-LAST:event_jButtonStuClearActionPerformed

    private void jButtonStuADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuADDActionPerformed
/*        try {
            DefaultTableModel modelStudent = (DefaultTableModel) jTableStuInfo.getModel();
            StudentInformation SI = new StudentInformation();
            String id = SI.jTextFieldStuID.getText();
            String name = SI.jTextFieldStuName.getText();
            String dept = (String) SI.jComboBoxClass.getSelectedItem();
            String sec = (String) jComboBoxSec.getSelectedItem();
            String major = (String) jComboBoxMajor.getSelectedItem();
            modelStudent.addRow(new Object[]{id, name, dept, sec, major});
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jButtonStuADDActionPerformed

    private void jButtonStuViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStuViewActionPerformed
        try {
            // "View" Button (Tab: Student Information)
            DefaultTableModel modelStudent = (DefaultTableModel) jTableStuInfo.getModel();
            String str = "SELECT StuID,StuName,Class,Section,Major FROM student_info";
            PreparedStatement Sta = DBCon.prepareStatement(str);

            ResultSet resultQuery = Sta.executeQuery();
            while (resultQuery.next()) {
                String ID = resultQuery.getString("StuID");
                String NAME = resultQuery.getString("StuName");
                String CLS = resultQuery.getString("Class");
                String SEC = resultQuery.getString("Section");
                String MAJ = resultQuery.getString("Major");
                modelStudent.addRow(new Object[]{ID, NAME, CLS, SEC, MAJ});
            }
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonStuViewActionPerformed

    private void jButtonBookClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookClearActionPerformed
        // "Clear" Button (Book Information)
        DefaultTableModel modelBook = (DefaultTableModel) jTableBookInfo.getModel();
        modelBook.setRowCount(0);
    }//GEN-LAST:event_jButtonBookClearActionPerformed

    private void jButtonBookADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookADDActionPerformed

    private void jButtonBookViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookViewActionPerformed
        try {
            // "View" Button (Book Information)
            DefaultTableModel modelBook = (DefaultTableModel) jTableBookInfo.getModel();
            String str = "SELECT * FROM book_info";
            PreparedStatement PS = DBCon.prepareStatement(str);
            ResultSet RS = PS.executeQuery();
            while (RS.next()) {
                modelBook.addRow(new Object[]{RS.getString("BookID"), RS.getString("BookTitle"), RS.getString("Class"), RS.getString("Edition"), RS.getString("Author"), RS.getString("Publication"), RS.getString("ISBN")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(IndexFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonBookViewActionPerformed

    private void jButtonTecClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTecClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTecClearActionPerformed

    private void jButtonTecADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTecADDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTecADDActionPerformed

    private void jButtonTecViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTecViewActionPerformed
        // "View" Button (Teacher Information)
        DefaultTableModel modelBook = (DefaultTableModel) jTableBookInfo.getModel();
        String str = "SELECT * FROM teacher_info";
    }//GEN-LAST:event_jButtonTecViewActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Open this form in Center
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoChart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InfoChart().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InfoChart.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookADD;
    private javax.swing.JButton jButtonBookClear;
    private javax.swing.JButton jButtonBookView;
    private javax.swing.JButton jButtonStuADD;
    private javax.swing.JButton jButtonStuClear;
    private javax.swing.JButton jButtonStuView;
    private javax.swing.JButton jButtonTecADD;
    private javax.swing.JButton jButtonTecClear;
    private javax.swing.JButton jButtonTecView;
    private javax.swing.JLabel jLabelTitleName;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBookInfo;
    private javax.swing.JPanel jPanelStuInfo;
    private javax.swing.JPanel jPanelTecInfo;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneIndexInfo;
    private javax.swing.JTable jTableBookInfo;
    private javax.swing.JTable jTableStuInfo;
    private javax.swing.JTable jTableStuInfo1;
    // End of variables declaration//GEN-END:variables
}
