package DemoApp;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Graphics2D;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.WritableRaster;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.coobird.thumbnailator.Thumbnails;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ud
 */
public class Demo2Folder extends javax.swing.JFrame {

    //////////////start of image var
    byte[] Person_image;
    private ImageIcon imagedata;
    ////////////////////////end of var

    Connection connection;
    PreparedStatement pst = null;
    ResultSet rs;

   

    ////******************
    private File image, doc1 = null, doc2 = null, doc3 = null, doc4 = null, doc5 = null, empPic = null;
    private File form;
    private File finalDistImageURL;
    private File finalDistFormURL, finalDistDoc1URL, finalDistDoc2URL, finalDistDoc3URL, finalDistDoc4URL, finalDistDoc5URL;
    String filename = null, doc1FileName = null, doc2FileName = null, doc3FileName = null, doc4FileName = null, doc5FileName = null;
    String formname = null, empPicName = null;
    BufferedImage resizeImageJpg;
    ImageIcon photo;
    WritableRaster raster;
    DataBufferByte imgDataBuffer;

    /////////
    String mainPath;

    File checkFile;

    // Image property
    private static final int IMG_WIDTH = 120;
    private static final int IMG_HEIGHT = 140;

    JFileChooser formChooser, imageChooser, doc1Chooser, doc2Chooser, doc3Chooser, doc4Chooser, doc5Chooser, employeePicChooser;

    private static final String FILE_PATH = "StudentPic/";
    // private static final String FILE_PATH = "F:/Document/";

    /**
     * Creates new form Demo
     *
     * @throws java.io.IOException
     */
    public Demo2Folder() throws IOException {
        try {
            initComponents();

            connection = DBConnection.DBConnection();

            // DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            // JTable table = new JTable(model);
            //  jTable1.add(table);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
        }

        AutoID();

        TableData();

        

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPhoto = new javax.swing.JLabel();
        buttonAddPhoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtimgLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonAddPhoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonAddPhoto.setText("Attach");
        buttonAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPhotoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(39, 39, 39)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtimgLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buttonAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtimgLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(302, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AutoID() {
        ///////// start of auto increment
        try {
            String id;
            String query5 = "select COALESCE(MAX(Sid),0) from student2";
            PreparedStatement st = connection.prepareStatement(query5);

            ResultSet res5 = st.executeQuery();
            while (res5.next()) {
                id = res5.getString("COALESCE(MAX(Sid),0)");
                int tt = Integer.parseInt(id);
                int ss1 = tt + 1;
                String ss5 = Integer.toString(ss1);
                txtID.setText(ss5);//Sales no
                //  labelClassId.setEditable(false);//sales no
                System.out.println(ss5);
            }
        } catch (SQLException | NumberFormatException ex1) {
            JOptionPane.showMessageDialog(null, ex1.toString());
        }//end try-catch

        /////////////// end of auto increment
    }

    private void TableData() {

        try {

            ///////// start of table data
            try {

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                String id;
                String query5 = "select * from student2";
                PreparedStatement st = connection.prepareStatement(query5);

                ResultSet res5 = st.executeQuery();
                while (res5.next()) {

                    // byte[] imaged = res5.getBytes("picture");
                    // imagedata = new ImageIcon(imaged);
                    // labelPhoto.setIcon(imagedata);
                    //, new ImageIcon(new ImageIcon(imaged).getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH))
                    model.addRow(new Object[]{res5.getString("Sid"), res5.getString("name")});
                }
            } catch (SQLException | NumberFormatException ex1) {
                JOptionPane.showMessageDialog(null, ex1.toString());
            }//end try-catch

            /////////////// end of table data
        } catch (Exception ex) {
            Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void buttonAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPhotoActionPerformed

        FileNameExtensionFilter filter;
        imageChooser = new JFileChooser();
        imageChooser.setCurrentDirectory(image);
        filter = new FileNameExtensionFilter("jpeg, gif and png files", "jpg", "gif", "png");
        imageChooser.addChoosableFileFilter(filter);

        int i = imageChooser.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            if (labelPhoto.getIcon() != null) {
                labelPhoto.removeAll();
            }
            image = imageChooser.getSelectedFile();
            filename = image.getAbsolutePath();
            String format = getTypeDescription(image);
            System.err.println("MAIN FORMAT " + format);
            if (format.equalsIgnoreCase("jpg") || format.equalsIgnoreCase("gif") || format.equalsIgnoreCase("png")) {
                try {
                    renamePhoto(format);
                } catch (URISyntaxException ex) {
                    Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                filename = null;
                JOptionPane.showMessageDialog(null, "Please Choose Correct Format of File As jpg,gif,png etc. ");
            }
        }


    }//GEN-LAST:event_buttonAddPhotoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            //save

            copyFile(image, finalDistImageURL);
        } catch (IOException ex) {
            Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            String sql = "INSERT INTO student2 (Sid, name, picture) VALUES ( ?, ?, ?)";
            PreparedStatement psti = connection.prepareStatement(sql);
            psti.setString(1, txtID.getText());
            psti.setString(2, txtName.getText());
            psti.setString(3, image.getName());

            psti.execute();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch (HeadlessException | SQLException e) {

        }//end try-catch

        AutoID();
        // TableData();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        // Search
        String query = "SELECT Sid,name,picture FROM student2 WHERE Sid = ? ";

        try {
            PreparedStatement psts = connection.prepareStatement(query);
            psts.setString(1, txtSearch.getText());
            ResultSet rss = psts.executeQuery();

            // DefaultTableModel model = (DefaultTableModel) jTableInformation.getModel();
            //  model.setRowCount(0);
            while (rss.next()) {

                txtID.setText(rss.getString("Sid"));
                txtName.setText(rss.getString("name"));

                String imagename = rss.getString("picture");

                ImageIcon getImage = resizedImage(FILE_PATH + imagename);
                labelPhoto.setIcon(getImage);

                /*
                 BufferedImage image = null;

                 image = ImageIO.read(new File(imagename));

                 checkFile = new File(imagename);
                 // if (checkFile.exists()) {
                 ImageIcon imageIcon = new ImageIcon(image);
                 //JLabel jLabel = new JLabel();
                 labelPhoto.setIcon(imageIcon);
                    
                 */
                //   }
                // byte[] imaged = rss.getBytes("picture");
                // imagedata = new ImageIcon(imaged);
                //labelPhoto.setIcon(imagedata);
                // model.addRow(new Object[]{rs.getString("Sid"),rs.getString("name")});
            }//end while

        } catch (SQLException ex) {
            Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    public void accessImageURL(String url) {

        mainPath = url;
    }


    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // clear
        txtName.setText("");
        labelPhoto.setText(null);
        txtimgLocation.setText("");
        txtSearch.setText("");

//        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        // model.setRowCount(0);
        AutoID();
        //TableData();


    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // update

            copyFile(image, finalDistImageURL);
        } catch (IOException ex) {
            Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {

            String str = "UPDATE student2 set name = ?, picture = ? WHERE Sid = ?";
            PreparedStatement pstu = connection.prepareStatement(str);

            pstu.setString(1, txtName.getText());
            pstu.setString(2, image.getName());

            pstu.setString(3, txtID.getText());
            pstu.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Successfully updated!!!!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

       // TableData();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // delete
        try {
            String str = "delete from student2 where Sid = ? ";
            PreparedStatement pstd = connection.prepareStatement(str);
            pstd.setString(1, txtID.getText());
            pstd.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data deleted!!!!");

        } catch (SQLException | HeadlessException e) {

        }

        txtName.setText("");
        labelPhoto.setText("");
        txtimgLocation.setText("");

        AutoID();
       // TableData();


    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo2Folder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo2Folder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo2Folder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo2Folder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Demo2Folder().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Demo2Folder.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton buttonAddPhoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtimgLocation;
    // End of variables declaration//GEN-END:variables

    /*
    
    
     public void createPDF(){

     Document d = new Document (PageSize.A4);
     try {
     PdfWriter.getInstance(d, new FileOutputStream("sample.pdf"));
     d.open ();
     d.addCreator("Sample Demo.java");
     d.addAuthor("Sundar");
     d.addTitle("First PDF By Sundar");
     //this is where you have to do your query to fetch image as BLOB from DB
     //Blob imageBlob = resultSet.getBlob(yourBlobColumnIndex);
     //byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
     Image image = Image.getInstance(imageBytes);
     image.scaleAbsolute(300,300);
     d.add(image);
     d.close ();
     } catch (Exception e) {
     e.printStackTrace();
     } 
     System.out.println("******** PDF Created ***************");

     }
    
     */
    /*
     public class TestPane extends JPanel {

     public TestPane() throws SQLException, IOException {
     setLayout(new BorderLayout());
     DefaultTableModel model = makeTableModel();
     JTable table = new JTable(model);
     table.setRowHeight(100);
     add(new JScrollPane(table));
     }

       

    
     }
     */
    private ImageIcon resizedImage(String imgPath) {
        File image = new File(imgPath);
        BufferedImage resizeImageJpg;
        ImageIcon photo = null;
        WritableRaster raster;
        DataBufferByte imgDataBuffer;

        try {
            BufferedImage originalImage = ImageIO.read(image);
            int type = originalImage.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

            resizeImageJpg = resizeImage(originalImage, type);
            photo = new ImageIcon(toImage(resizeImageJpg));

            //converting buffered image to byte array
            raster = resizeImageJpg.getRaster();
            imgDataBuffer = (DataBufferByte) raster.getDataBuffer();

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
        return photo;
    }

    ////////
    private static void copyFile(File source, File dest)
            throws IOException {
        Files.copy(source.toPath(), dest.toPath());
    }

    private static BufferedImage resizeImage(BufferedImage originalImage, int type) {
        BufferedImage resizedImage = new BufferedImage(IMG_WIDTH, IMG_HEIGHT, type);
        Graphics2D g = resizedImage.createGraphics();
        g.drawImage(originalImage, 0, 0, IMG_WIDTH, IMG_HEIGHT, null);
        g.dispose();

        return resizedImage;
    }

    private Image toImage(BufferedImage bufferedImage) {
        return Toolkit.getDefaultToolkit().createImage(bufferedImage.getSource());
    }

    public void renamePhoto(String ext) throws URISyntaxException {

        Calendar c = Calendar.getInstance();
        String s = dateToString(c);

        String newName = txtName.getText().toString() + s + "." + ext;
        String newPath = filename.replaceAll("\\\\", "/");

        int len = image.getName().length();
        System.err.println("Length: " + len);

        String root = newPath.substring(0, 2);
        System.err.println("parent: " + root);

        String newFileName = root + "//" + newPath.substring(3, (newPath.length() - len)) + newName.replaceAll(" ", "_");
        System.err.println("New Path: " + newFileName);
        File newFinalFile = new File(newFileName);

        if (image.renameTo(newFinalFile)) {
//            try {
//                String jarURL = getClass().getProtectionDomain().getCodeSource().getLocation().toURI().getPath().toString();
//                jarURL = jarURL.replaceAll("\\\\", "/");
//                jarURL = jarURL.substring(1, jarURL.length() - 14) + "Document/";
            System.out.println("PathJAR: " + FILE_PATH);
            //File test = new File(jarURL + newFinalFile.getName().toString

            File test = new File(FILE_PATH + newFinalFile.getName().toString());

            finalDistImageURL = test;
            //copyFile(newFinalFile, test);

            System.out.println("renamed");
//            } catch (URISyntaxException ex) {
//                Logger.getLogger(AdmissionForm.class.getName()).log(Level.SEVERE, null, ex);
//            }
        } else {
            System.out.println("Error");
        }

        image = newFinalFile;
        filename = image.getAbsolutePath();
        //System.err.println("Main Path: "+filename);
        System.out.println("After renaming correct path is: " + filename);

        /**
         * *******************************************
         */
        try {
            BufferedImage originalImage = ImageIO.read(image);
            int type = originalImage.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : originalImage.getType();

            resizeImageJpg = resizeImage(originalImage, type);
            photo = new ImageIcon(toImage(resizeImageJpg));

            //converting buffered image to byte array
            raster = resizeImageJpg.getRaster();
            imgDataBuffer = (DataBufferByte) raster.getDataBuffer();

            labelPhoto.setIcon(photo);

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }

        imageChooser.setCurrentDirectory(image);

    }

    public String getTypeDescription(File f) {
        String extension = Utils.getExtension(f);
        String type = null;

        if (extension != null) {
            switch (extension) {
                case Utils.jpeg:
                case Utils.jpg:
                    type = "jpg";
                    break;
                case Utils.gif:
                    type = "gif";
                    break;
                case Utils.tiff:
                case Utils.tif:
                    type = "tiff";
                    break;
                case Utils.png:
                    type = "png";
                    break;
                case Utils.doc:
                    type = "doc";
                    break;
                case Utils.docx:
                    type = "docx";
                    break;
                case Utils.pdf:
                    type = "pdf";
                    break;
            }
        }
        return type;
    }

    private static String dateToString(Calendar cal) {
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        dateFormat.format(cal.getTime());
        String data1 = String.valueOf(cal.get(Calendar.YEAR));
        String data2 = String.valueOf(cal.get(Calendar.MONTH) + 1);
        String data3 = String.valueOf(cal.get(Calendar.DATE));
        String data4 = String.valueOf(cal.get(Calendar.HOUR));
        String data5 = String.valueOf(cal.get(Calendar.MINUTE));
        String data6 = String.valueOf(cal.get(Calendar.SECOND));

        return data1 + data2 + data3 + data4 + data5 + data6;
    }

    public static void fileCopy(File source, File dest) throws IOException {
        if (!dest.exists()) {
            dest.createNewFile();
        }
        InputStream in = null;
        OutputStream out = null;
        try {
            in = new FileInputStream(source);
            out = new FileOutputStream(dest);

            // Transfer bytes from in to out
            byte[] buf = new byte[1024];
            int len;
            while ((len = in.read(buf)) > 0) {
                out.write(buf, 0, len);
            }
        } finally {
            if (in != null) {
                in.close();
            }
            if (out != null) {
                out.close();
            }
        }
    }

}
