package DemoApp;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.coobird.thumbnailator.Thumbnails;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Ud
 */
public class Demo extends javax.swing.JFrame {
    
    private static int counter = 0;

    //////////////start of image var
    String filename;
    byte[] Person_image;
    private ImageIcon imagedata;
    ////////////////////////end of var

    Connection connection;
    PreparedStatement pst = null;
    ResultSet rs;

    // the index of the items
    int pos = 0;

    /**
     * Creates new form Demo
     *
     * @throws java.io.IOException
     */
    public Demo() throws IOException {

        try {
            initComponents();

            connection = DBConnection.DBConnection();

            // DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
            // JTable table = new JTable(model);
            //  jTable1.add(table);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }

        AutoID();

        TableData();

        // display the first item
        showItem(pos);

        CurrentDate();
    }

    ///////////////date time
    public void CurrentDate() {

        Thread clock = new Thread() {
            public void run() {

                for (;;) {

                    ///////////
                    Calendar cal = new GregorianCalendar();
                    int month = cal.get(Calendar.MONTH);
                    int year = cal.get(Calendar.YEAR);
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    date_txt.setText("Date: " + year + "/" + (month + 1) + "/" + day);

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    txt_time.setText("Time:  " + hour + ":" + (minute) + ":" + second);

                    //////////////
                    try {

                        sleep(500);
                    } catch (InterruptedException e) {

                    }

                }

            }

        };
        clock.start();
        

        
    }

    //////////////
    ShowFromJtableinFrame jtRowData = new ShowFromJtableinFrame();

    // bind a list of item from mysql database
    public List<Item> getItemsList() {
        try {
            // Connection connection = getConnection();

            // Statement st = connection.createStatement();
            String qry = "SELECT * FROM student";

            PreparedStatement st = connection.prepareStatement(qry);

            ResultSet res5 = st.executeQuery();

            List<Item> list = new ArrayList<Item>();

            Item item;

            while (res5.next()) {
                item = new Item(res5.getString("Sid"), res5.getString("name"),
                        res5.getBytes("picture"));

                list.add(item);
            }
            return list;

        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    // show records and image from database 
    public void showItem(int index) {
        txtID.setText(getItemsList().get(index).getId());

        txtName.setText(getItemsList().get(index).getName());

        ImageIcon icon = new ImageIcon(getItemsList().get(index).getImage());

        Image image2 = icon.getImage().getScaledInstance(labelPhoto.getWidth(),
                labelPhoto.getHeight(), Image.SCALE_SMOOTH);

        labelPhoto.setIcon(new ImageIcon(image2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPhoto = new javax.swing.JLabel();
        buttonAddPhoto = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtimgLocation = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnFirst = new javax.swing.JButton();
        btnPrvious = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnDeleteSelectedRow = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnSelect = new javax.swing.JButton();
        btnAddRow = new javax.swing.JButton();
        date_txt = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        btnUpdateTable = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelPhoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonAddPhoto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonAddPhoto.setText("Attach");
        buttonAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddPhotoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnSearch)
                        .addGap(18, 18, 18)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtID)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnPrint.setText("Print");

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrint))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addGap(39, 39, 39)
                        .addComponent(btnDelete)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name"
            }
        ));
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnFirst.setText("First");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrvious.setText("Previous");
        btnPrvious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrviousActionPerformed(evt);
            }
        });

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFirst)
                .addGap(41, 41, 41)
                .addComponent(btnNext)
                .addGap(38, 38, 38)
                .addComponent(btnPrvious)
                .addGap(27, 27, 27)
                .addComponent(btnLast)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnNext)
                    .addComponent(btnPrvious)
                    .addComponent(btnLast))
                .addContainerGap())
        );

        btnDeleteSelectedRow.setText("Delete Selected Row");
        btnDeleteSelectedRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSelectedRowActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL", "ID", "Name"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        btnSelect.setText("select");
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });

        btnAddRow.setText("Add Row");
        btnAddRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRowActionPerformed(evt);
            }
        });

        date_txt.setText("Date:");

        txt_time.setText("Time: ");

        btnUpdateTable.setText("Update Table");
        btnUpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSelect))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 152, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnUpdateTable)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtimgLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(buttonAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(77, 77, 77))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(btnDeleteSelectedRow, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAddRow)
                                .addGap(231, 231, 231))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addComponent(txt_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnDeleteSelectedRow))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtimgLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(buttonAddPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddRow)
                            .addComponent(btnUpdateTable))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSelect)
                        .addGap(78, 78, 78)))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AutoID() {
        ///////// start of auto increment
        try {
            String id;
            String query5 = "select COALESCE(MAX(Sid),0) from student";
            PreparedStatement st = connection.prepareStatement(query5);

            ResultSet res5 = st.executeQuery();
            while (res5.next()) {
                id = res5.getString("COALESCE(MAX(Sid),0)");
                int tt = Integer.parseInt(id);
                int ss1 = tt + 1;
                String ss5 = Integer.toString(ss1);
                txtID.setText(ss5);//Sales no
                //  labelClassId.setEditable(false);//sales no
                System.out.println(ss5);
            }
        } catch (SQLException | NumberFormatException ex1) {
            JOptionPane.showMessageDialog(null, ex1.toString());
        }//end try-catch

        /////////////// end of auto increment
    }

    private void TableData() {

        try {

            ///////// start of table data
            try {

                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);

                String id;
                String query5 = "select * from student";
                PreparedStatement st = connection.prepareStatement(query5);

                ResultSet res5 = st.executeQuery();
                while (res5.next()) {

                    // byte[] imaged = res5.getBytes("picture");
                    // imagedata = new ImageIcon(imaged);
                    // labelPhoto.setIcon(imagedata);
                    //, new ImageIcon(new ImageIcon(imaged).getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH))
                    model.addRow(new Object[]{res5.getString("Sid"), res5.getString("name")});
                }
            } catch (SQLException | NumberFormatException ex1) {
                JOptionPane.showMessageDialog(null, ex1.toString());
            }//end try-catch

            /////////////// end of table data
        } catch (Exception ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void buttonAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddPhotoActionPerformed

        /*
         FileFilter filter = new FileNameExtensionFilter("Picture File", "jpg", "jpeg", "png", "bmp", "gif");
         JFileChooser fileChoooser = new JFileChooser();
         fileChoooser.addChoosableFileFilter(filter);
         fileChoooser.setDialogTitle("Chooose Your Image File");
         fileChoooser.setFileSelectionMode(JFileChooser.FILES_ONLY);

         int returnValue = fileChoooser.showOpenDialog(this);
         if (returnValue == JFileChooser.APPROVE_OPTION) {
         File file = fileChoooser.getSelectedFile();
         //Thumbnails.of(file).size(100, 100)
         BufferedImage bufferImage;
         try {
         bufferImage = ImageIO.read(file);

         //
         int width = labelPhoto.getWidth() - 2;
         int height = labelPhoto.getHeight() - 2;
         BufferedImage bi = new BufferedImage(width, height, BufferedImage.TRANSLUCENT);
         Graphics2D g2d = (Graphics2D) bi.createGraphics();
         g2d.addRenderingHints(new RenderingHints(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY));
         g2d.drawImage(bufferImage, 0, 0, width, height, null);
         g2d.dispose();
         //

         labelPhoto.setIcon(new ImageIcon(bi));
         } catch (IOException ex) {
         Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
         }
         }

         */
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        txtimgLocation.setText(filename);
        try {
            File image1 = new File(filename);
            BufferedImage bufferedImage = ImageIO.read(image1);
            BufferedImage thumbnail = Thumbnails.of(bufferedImage).size(150, 150).asBufferedImage();

            ByteArrayOutputStream bos = new ByteArrayOutputStream();

            ImageIO.write(thumbnail, "jpeg", bos);

            ByteArrayInputStream is = new ByteArrayInputStream(bos.toByteArray());

            byte[] buf = new byte[1024];

            for (int readNum; (readNum = is.read(buf)) != -1;) {
                bos.write(buf, 0, readNum);
                //  System.out.println("Read " + readNum + "bytes");
            }
            Person_image = bos.toByteArray();

            //  Image image=bufferedImage.toImage(true);  //this generates an image file
            ImageIcon icon = new ImageIcon(thumbnail);

            labelPhoto.setIcon(icon);

        } catch (Exception e) {
            System.out.println("Attach Error Caught: " + e);
        }


    }//GEN-LAST:event_buttonAddPhotoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        //save

        try {

            String sql = "INSERT INTO student (Sid, name, picture) VALUES ( ?, ?, ?)";
            PreparedStatement psti = connection.prepareStatement(sql);
            psti.setString(1, txtID.getText());
            psti.setString(2, txtName.getText());
            psti.setBytes(3, Person_image);

            psti.execute();
            JOptionPane.showMessageDialog(null, "Saved");

        } catch (HeadlessException | SQLException e) {

        }//end try-catch

        AutoID();
        // TableData();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        // Search
        String query = "SELECT Sid,name,picture FROM student WHERE Sid = ? ";

        try {
            PreparedStatement psts = connection.prepareStatement(query);
            psts.setString(1, txtSearch.getText());
            ResultSet rss = psts.executeQuery();

            // DefaultTableModel model = (DefaultTableModel) jTableInformation.getModel();
            //  model.setRowCount(0);
            while (rss.next()) {

                txtID.setText(rss.getString("Sid"));
                txtName.setText(rss.getString("name"));

                byte[] imaged = rss.getBytes("picture");
                imagedata = new ImageIcon(imaged);
                labelPhoto.setIcon(imagedata);

                // model.addRow(new Object[]{rs.getString("Sid"),rs.getString("name")});
            }//end while

        } catch (SQLException ex) {
            Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // clear
        txtName.setText("");
        labelPhoto.setText(null);
        txtimgLocation.setText("");
        txtSearch.setText("");

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
       // AutoID();
        //TableData();


    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // update
        try {

            String str = "UPDATE student set name = ?, picture = ? WHERE Sid = ?";
            PreparedStatement pstu = connection.prepareStatement(str);

            pstu.setString(1, txtName.getText());
            pstu.setBytes(2, Person_image);

            pstu.setString(3, txtID.getText());
            pstu.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Successfully updated!!!!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }

       // TableData();

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // delete

        int p = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete", JOptionPane.YES_NO_OPTION);
        if (p == 0) {

            try {
                String str = "delete from student where Sid = ? ";
                PreparedStatement pstd = connection.prepareStatement(str);
                pstd.setString(1, txtID.getText());
                pstd.executeUpdate();

                JOptionPane.showMessageDialog(null, "Data deleted!!!!");

            } catch (SQLException | HeadlessException e) {

            }

        }

        txtName.setText("");
        labelPhoto.setText("");
        txtimgLocation.setText("");

        AutoID();
       // TableData();


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // first
        pos = 0;
        showItem(pos);
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrviousActionPerformed
        // previous
        pos--;
        if (pos < 0) {
            pos = 0;
        }
        showItem(pos);
    }//GEN-LAST:event_btnPrviousActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // Last
        pos = getItemsList().size() - 1;
        showItem(pos);
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // next
        pos++;
        if (pos >= getItemsList().size()) {
            pos = getItemsList().size() - 1;
        }
        showItem(pos);
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDeleteSelectedRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSelectedRowActionPerformed
        // delete selected row

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // get selected row index
        try {
            int SelectedRowIndex = jTable1.getSelectedRow();
            model.removeRow(SelectedRowIndex);
        } catch (Exception ex) {
           // JOptionPane.showMessageDialog(null, ex);
            System.err.println("Delete Row Exception: "+ex);
        }
    }//GEN-LAST:event_btnDeleteSelectedRowActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        // select data for other table
        TableModel model1 = jTable1.getModel();

        int[] indexs = jTable1.getSelectedRows();

        Object[] row = new Object[2];
        // Object[] row = new Object[4];

        DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

        for (int i = 0; i < indexs.length; i++) {
            row[0] = model1.getValueAt(indexs[i], 0);

            row[1] = model1.getValueAt(indexs[i], 1);

            // row[2] = model1.getValueAt(indexs[i], 2);
            // row[3] = model1.getValueAt(indexs[i], 3);
            model2.addRow(row);
        }
    }//GEN-LAST:event_btnSelectActionPerformed

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        // table click

        // Search
        if ((evt.getKeyCode() == KeyEvent.VK_UP) || (evt.getKeyCode() == KeyEvent.VK_DOWN)) {

            try {
                int row = jTable1.getSelectedRow();
                String Table_click = (jTable1.getModel().getValueAt(row, 0).toString());

                String query = "SELECT Sid,name,picture FROM student WHERE Sid = ? ";
                PreparedStatement psts = connection.prepareStatement(query);
                psts.setString(1, Table_click);
                ResultSet rss = psts.executeQuery();

                // DefaultTableModel model = (DefaultTableModel) jTableInformation.getModel();
                //  model.setRowCount(0);
                while (rss.next()) {

                    txtID.setText(rss.getString("Sid"));
                    txtName.setText(rss.getString("name"));

                    byte[] imaged = rss.getBytes("picture");
                    imagedata = new ImageIcon(imaged);
                    labelPhoto.setIcon(imagedata);

                    // model.addRow(new Object[]{rs.getString("Sid"),rs.getString("name")});
                }//end while

            } catch (SQLException ex) {
                Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jTable1KeyReleased

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:

        int index = jTable2.getSelectedRow();

        TableModel model = jTable2.getModel();

        String id = model.getValueAt(index, 1).toString();
        String firstName = model.getValueAt(index, 2).toString();
        //String lastName = model.getValueAt(index, 2).toString();
        //String age = model.getValueAt(index, 3).toString();

        jtRowData.setVisible(true);
        jtRowData.pack();
        jtRowData.setLocationRelativeTo(null);
        jtRowData.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jtRowData.txtID.setText(id);
        jtRowData.txtName.setText(firstName);
        
        
        ////////////////show data on current frame text field
        
        // Get The Index Of The Slected Row 
        int i = jTable2.getSelectedRow();

        
        
         // Display Slected Row In JTexteFields
        txtID.setText(model.getValueAt(i,1).toString());

        txtName.setText(model.getValueAt(i,2).toString());
        
        
        /////////////////
        


    }//GEN-LAST:event_jTable2MouseClicked

    private void btnAddRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRowActionPerformed
        // TODO add your handling code here:

        // get the model from the jtable
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        // insert row to the model from jtextfields using addRow method
      //  model.addRow(new Object[]{txtID.getText(), txtName.getText()});
        
        ///////////////////////add SL
        
      /*   
        if (!this.txtID.getText().isEmpty()) {
            int row = model.getRowCount();
            Object rowCount = ++row;
            Object Name = this.txtName.getText();
            Object[] n = {rowCount, txtID.getText(),Name};
            model.addRow(n);
        }
        
        */
        ///////////////check duplicate and set serial no
        int row1 = model.getRowCount();
        Object rowCount = ++row1;
        
        String SL = String.valueOf(++counter);
        String id=txtID.getText();
        String name = txtName.getText();
        

        Object[] row = {rowCount, id, name};
        

        String s = "";
        boolean exists = false;
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            s = jTable2.getValueAt(i, 1).toString().trim();
            System.out.println("******Column Value: " + s);
            if (id.equals(s)) {
                exists = true;
                break;
            }
        }
        if (!exists) {
            model.addRow(row);
        } else {
            JOptionPane.showMessageDialog(null, "Data already exist.", "Warning", JOptionPane.PLAIN_MESSAGE);
        }
        
        
        
        ////////////
        
        
        
    }//GEN-LAST:event_btnAddRowActionPerformed

    private void btnUpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTableActionPerformed
        // update table data
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int i = jTable2.getSelectedRow();
        if(i>=0){
            model.setValueAt(txtID.getText(), i, 1);
            model.setValueAt(txtName.getText(), i, 2);
        }else{
            System.err.println("Update Error ");
        }
        
    }//GEN-LAST:event_btnUpdateTableActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Demo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Demo().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRow;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteSelectedRow;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnPrvious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateTable;
    private javax.swing.JButton buttonAddPhoto;
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelPhoto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JLabel txt_time;
    private javax.swing.JTextField txtimgLocation;
    // End of variables declaration//GEN-END:variables

    /*
    
    
     public void createPDF(){

     Document d = new Document (PageSize.A4);
     try {
     PdfWriter.getInstance(d, new FileOutputStream("sample.pdf"));
     d.open ();
     d.addCreator("Sample Demo.java");
     d.addAuthor("Sundar");
     d.addTitle("First PDF By Sundar");
     //this is where you have to do your query to fetch image as BLOB from DB
     //Blob imageBlob = resultSet.getBlob(yourBlobColumnIndex);
     //byte[] imageBytes = imageBlob.getBytes(1, (int) imageBlob.length());
     Image image = Image.getInstance(imageBytes);
     image.scaleAbsolute(300,300);
     d.add(image);
     d.close ();
     } catch (Exception e) {
     e.printStackTrace();
     } 
     System.out.println("******** PDF Created ***************");

     }
    
     */
    /*
     public class TestPane extends JPanel {

     public TestPane() throws SQLException, IOException {
     setLayout(new BorderLayout());
     DefaultTableModel model = makeTableModel();
     JTable table = new JTable(model);
     table.setRowHeight(100);
     add(new JScrollPane(table));
     }

       

    
     }
     */
    ////////
}
