/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DemoApp;

import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ud
 */
public class ShowTableImage extends javax.swing.JFrame {

    Connection connection;

    /**
     * Creates new form ShowTableImage
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     * @throws java.io.IOException
     */
    public ShowTableImage() throws ClassNotFoundException, SQLException, IOException {
        super("Show Image in Table");
        
        initComponents();
        

        connection = DBConnection.DBConnection();

        ///////////////////////
        setLayout(new BorderLayout());
        DefaultTableModel model = makeTableModel();
        JTable table = new JTable(model);
        table.setRowHeight(100);
        add(new JScrollPane(table));
//////////////////////////
        //  TableDataImage();
    }

   

    /*
     private void TableDataImage() {

     try {
            
     /////////////// end of table data
     setLayout(new BorderLayout());
     DefaultTableModel model = makeTableModel();
     JTable table = new JTable(model);
     table.setRowHeight(100);
     // table.setRowHeight(50);
     add(new JScrollPane(table));
     } catch (SQLException | IOException ex) {
     Logger.getLogger(Demo.class.getName()).log(Level.SEVERE, null, ex);
     }

     }
     
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowTableImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowTableImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowTableImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowTableImage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ShowTableImage().setVisible(true);
                } catch (ClassNotFoundException | SQLException | IOException ex) {
                    Logger.getLogger(ShowTableImage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    
     protected DefaultTableModel makeTableModel() throws SQLException, IOException {
        DefaultTableModel model = new DefaultTableModel(new String[]{"Name", "Image"}, 0) {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnIndex == 1 ? Icon.class : super.getColumnClass(columnIndex);
            }

        };

        String query = "select name,picture from student";
        // try (Connection con = makeConnection()) {
        PreparedStatement stmt = connection.prepareStatement(query);
        ResultSet rs3 = stmt.executeQuery();
        while (rs3.next()) {
            //String id = rs3.getString(1);
            String name = rs3.getString("name");
            Blob blob = rs3.getBlob("picture");
            ImageIcon icon = null;
            InputStream is = blob.getBinaryStream();
            BufferedImage img = ImageIO.read(is);
            icon = new ImageIcon(img);

            model.addRow(new Object[]{name, icon});
        }
        //}
        // }
        //}
        return model;

    }
    
    
    
    
}
