package DemoApp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.Image;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author it zone
 */
public class StudentViewPic2Folder extends javax.swing.JFrame {

    Connection connection;
    PreparedStatement pst = null;
    ResultSet rs;

    java.util.Date now = new java.util.Date();
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MMMM/yyyy");
    SimpleDateFormat sdftime = new SimpleDateFormat("hh:mm:ss a");
    DecimalFormat df1 = new DecimalFormat("#.##");

    ////******************
    private File doc1 = null, doc2 = null, doc3 = null, doc4 = null, doc5 = null, empPic = null;
    private File form;
    private File finalDistImageURL;
    private File finalDistFormURL, finalDistDoc1URL, finalDistDoc2URL, finalDistDoc3URL, finalDistDoc4URL, finalDistDoc5URL;
    String filename = null, doc1FileName = null, doc2FileName = null, doc3FileName = null, doc4FileName = null, doc5FileName = null;
    String formname = null, empPicName = null;
    BufferedImage resizeImageJpg;
    ImageIcon photo;
    WritableRaster raster;
    DataBufferByte imgDataBuffer;

    /////////
    String mainPath;

    File checkFile;
    Image image;

    // Image property
    private static final int IMG_WIDTH = 120;
    private static final int IMG_HEIGHT = 140;

    JFileChooser formChooser, imageChooser, doc1Chooser, doc2Chooser, doc3Chooser, doc4Chooser, doc5Chooser, employeePicChooser;

    private static final String FILE_PATH = "StudentPic/";
    // private static final String FILE_PATH = "F:/Document/";

    /**
     * Creates new form ResultCard
     *
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public StudentViewPic2Folder() throws ClassNotFoundException, SQLException {

        initComponents();

        connection = DBConnection.DBConnection();

    }

    ////////////////////////
    ////////////////////////////
/////////////////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        textFieldStudentIdForSearch = new javax.swing.JTextField();
        btnShowInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Student Profile File Pic", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Student ID : ");

        textFieldStudentIdForSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldStudentIdForSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldStudentIdForSearchKeyTyped(evt);
            }
        });

        btnShowInfo.setText("View");
        btnShowInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(28, 28, 28)
                        .addComponent(textFieldStudentIdForSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnShowInfo)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(textFieldStudentIdForSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnShowInfo)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowInfoActionPerformed
        StudentInfopicFile();
        if (Desktop.isDesktopSupported()) {
            try {
                File myfile = new File("StudentInfoPicFile.pdf");

                Desktop.getDesktop().open(myfile);
            } catch (IOException ioEx) {
                JOptionPane.showMessageDialog(null, ioEx.toString());
            }
        }

    }//GEN-LAST:event_btnShowInfoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void textFieldStudentIdForSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldStudentIdForSearchKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_textFieldStudentIdForSearchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentViewPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentViewPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentViewPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentViewPic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new StudentViewPic2Folder().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(StudentViewPic.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowInfo;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField textFieldStudentIdForSearch;
    // End of variables declaration//GEN-END:variables
//////////////////////////

    void StudentInfopicFile() {
        Document document = new Document(PageSize.A4.rotate());

        //   Rectangle layout = new Rectangle(PageSize.A4.rotate());
        //layout.setBackgroundColor(new Color(100, 200, 180)); //Background color
        // layout.setBorderColor(Color.BLACK);  //Border color
        //  layout.setBorderWidth(2);
        // layout.setBorderWidth(6);
        //Border width
        // layout.setBorderWidthTop(3);
        // layout.setBorder(Rectangle.BOX);  //Border on 4 sides
        // Document document = new Document(layout)
        //  Document document = new Document(layout);
        PdfPCell cell = new PdfPCell();
        Font ff1 = new Font(Font.BOLD, 15);
        ff1.setColor(Color.BLACK);

        ff1.setStyle(Font.BOLD);
        Font ff3 = new Font(Font.BOLD, 10);

        Paragraph paragraph3 = new Paragraph("\n");
        paragraph3.setAlignment(Element.ALIGN_CENTER);

        ///////variable declaration
        String StdName = "";

        /////////////////////////end of variable declaration
        try {

            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("StudentInfoPicFile.pdf"));

            document.open();

            String imageUrl = "pic/banner.PNG";
            // Image image = Image.getInstance(new URL(imageUrl));

            Image imageb = Image.getInstance(imageUrl);

            imageb.scaleAbsolute(590f, 590f);
            imageb.scaleAbsoluteHeight(85f);
            // image.scaleAbsoluteWidth(100f);

            PdfPTable tableLogo = new PdfPTable(1);
            tableLogo.setWidthPercentage(105);
            PdfPCell table_cellpi = new PdfPCell();

            table_cellpi = new PdfPCell(imageb, false);
            table_cellpi.setHorizontalAlignment(Element.ALIGN_CENTER);
            table_cellpi.setBorder(0);
            tableLogo.addCell(table_cellpi);

            //student info
            String stname = "";
            String id = "";

            Blob imageBlob;
            
            ImageIcon getImage;
            byte[] imageBytes = null;

            try {
                PreparedStatement pstm;
                ResultSet rsm;

                String query = "SELECT * FROM student2 WHERE Sid = ? ";

                pstm = connection.prepareStatement(query);

                pstm.setString(1, textFieldStudentIdForSearch.getText());

                rsm = pstm.executeQuery();

                if (rsm.next()) {

                    //  slNo++;
                    stname = rsm.getString("name");
                    id = rsm.getString("Sid");

                    mainPath = rsm.getString("picture");

                    //getImage = resizedImage(FILE_PATH + mainPath);
                   // labelPhoto.setIcon(getImage);

                }
            } catch (Exception e) {
            }

            //////////////////////
            PdfPCell cell1 = new PdfPCell();
            PdfPCell cell2 = new PdfPCell();
            PdfPCell cell3 = new PdfPCell();
            PdfPCell cell4 = new PdfPCell();
            PdfPCell cell5 = new PdfPCell();
            PdfPCell cell6 = new PdfPCell();

            PdfPTable my_report_table2 = new PdfPTable(1);
            my_report_table2.setWidthPercentage(80f);

            //Title Result
            cell2.setPhrase(new Phrase("Student Profile", new Font(Font.BOLD, 18, Font.BOLD, Color.RED)));
            cell2.setHorizontalAlignment(Element.ALIGN_CENTER);
            // cell2.setGrayFill(0.9f);
            cell2.setBorder(Rectangle.NO_BORDER);
            my_report_table2.addCell(cell2);

            PdfPTable my_report_table3 = new PdfPTable(1);
            my_report_table3.setWidthPercentage(40f);

            //float[] columnWidths1 = {3f,  1f};
            // my_report_table3.setWidths(columnWidths1);
            cell4.setPhrase(new Phrase("ID: " + id, new Font(Font.NORMAL, 14, Font.BOLD)));
            cell4.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell4.setGrayFill(0.9f);
            cell4.setBorderColor(Color.WHITE);
            //cell3.setBorder(Rectangle.NO_BORDER);
            my_report_table3.addCell(cell4);

            cell4.setPhrase(new Phrase("Name: " + stname, new Font(Font.NORMAL, 14, Font.BOLD)));
            cell4.setHorizontalAlignment(Element.ALIGN_LEFT);
            cell4.setGrayFill(0.9f);
            // cell4.setBorder(Rectangle.NO_BORDER);
            cell4.setBorderColor(Color.WHITE);
            my_report_table3.addCell(cell4);

            Image image1 = Image.getInstance(FILE_PATH + mainPath);
            image1.scaleAbsolute(150, 150);
           // image.scaleAbsolute(120, 120);
            ////////////

            
            //add table
            document.add(tableLogo);//add logo
            document.add(my_report_table2); //Title
            document.add(paragraph3); //new line

            document.add(image1);//image

            document.add(paragraph3); //new line
            document.add(my_report_table3);//name

            //  document.add(paragraph3);//total mark percentage/merit/working day/present
        } catch (DocumentException | IOException e56) {
            System.err.println(e56.getMessage());
        }

        document.close();

    }



}
